# Copyright (c) 2021 ETH Zurich
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

status = [
  "github/linux/debug/fast",
  "github/linux/fetchcontent/fast",
  "github/linux/hip/fast",
  "github/linux/sanitizers/fast",
  "ci/circleci: check_circular_deps",
  "ci/circleci: check_module_cmakelists",
  "ci/circleci: clang_format",
  "ci/circleci: cmake_format",
  "ci/circleci: configure",
  "ci/circleci: configure_test_combinations",
  "ci/circleci: inspect",
  "ci/circleci: core",
]
required_approvals = 0
delete_merged_branches = true
use_squash_merge = false
