---
exclude_paths:
  - "tools/perftests_ci/**"
  - ".jenkins/cscs-ault/env-*.sh"
  - ".jenkins/cscs-ault/config-*.sh"
  - ".jenkins/cscs/env-*.sh"
  - ".jenkins/cscs/config-*.sh"
  - ".jenkins/cscs-perftests/env-*.sh"
  - ".jenkins/cscs-perftests/config-*.sh"
