# Copyright (c) 2023 ETH Zurich
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file BOOST_LICENSE_1_0.rst or copy at http://www.boost.org/LICENSE_1_0.txt)

.rules_to_run_on_merge:
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH =~ /^gh-readonly-queue/ || $CI_COMMIT_BRANCH =~ /^release/

include:
  - local: '.gitlab/includes/gcc13_pipeline.yml'
  - local: '.gitlab/includes/clang14_cuda11_pipeline.yml'
  - local: '.gitlab/includes/performance_gcc13_pipeline.yml'
  - local: '.gitlab/includes/gcc12_hip5_pipeline.yml'
  # The pipelines below are running only on main, release and on merge queues
  - local: '.gitlab/includes/dockerhub_pipeline.yml'
    extends: .rules_to_run_on_merge
  - local: '.gitlab/includes/gcc9_pipeline.yml'
    extends: .rules_to_run_on_merge
  - local: '.gitlab/includes/gcc9_cuda11_pipeline.yml'
    extends: .rules_to_run_on_merge
  - local: '.gitlab/includes/gcc10_apex_pipeline.yml'
    extends: .rules_to_run_on_merge
  - local: '.gitlab/includes/gcc11_pipeline.yml'
    extends: .rules_to_run_on_merge
  - local: '.gitlab/includes/gcc12_pipeline.yml'
    extends: .rules_to_run_on_merge
  - local: '.gitlab/includes/gcc12_cuda12_pipeline.yml'
    extends: .rules_to_run_on_merge
  - local: '.gitlab/includes/clang11_pipeline.yml'
    extends: .rules_to_run_on_merge
  - local: '.gitlab/includes/clang12_pipeline.yml'
    extends: .rules_to_run_on_merge
  - local: '.gitlab/includes/clang13_pipeline.yml'
    extends: .rules_to_run_on_merge
  - local: '.gitlab/includes/clang15_pipeline.yml'
    extends: .rules_to_run_on_merge
  - local: '.gitlab/includes/clang16_pipeline.yml'
    extends: .rules_to_run_on_merge
  - local: '.gitlab/includes/clang17_pipeline.yml'
    extends: .rules_to_run_on_merge
