# Copyright (c) 2023 ETH Zurich
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

name: Linux CI (valgrind)

on:
  merge_group:
  pull_request:
  push:
    branches:
      # Development and release branches
      - main
      - release**
      # Bors branches
      - trying
      - staging

jobs:
  build:
    name: github/linux/valgrind
    runs-on: ubuntu-latest
    container: pikaorg/pika-ci-base:20

    strategy:
      matrix:
        build_type: ["Debug", "Release"]

    steps:
      - uses: actions/checkout@v4
      - name: Update apt repositories for ccache
        run: apt update
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ccache-linux-valgrind
      - name: Configure
        shell: bash
        # -gdwarf-4 because of https://github.com/llvm/llvm-project/issues/56550
        run: |
            cmake \
                . \
                -Bbuild \
                -GNinja \
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DCMAKE_CXX_FLAGS="-gdwarf-4" \
                -DPIKA_WITH_MALLOC=system \
                -DPIKA_WITH_EXAMPLES=ON \
                -DPIKA_WITH_TESTS=ON \
                -DPIKA_WITH_TESTS_EXAMPLES=ON \
                -DPIKA_WITH_TESTS_EXTERNAL_BUILD=OFF \
                -DPIKA_WITH_TESTS_HEADERS=OFF \
                -DPIKA_WITH_TESTS_MAX_THREADS=$(nproc) \
                -DPIKA_WITH_VALGRIND=ON \
                -DPIKA_WITH_TESTS_VALGRIND=ON \
                -DPIKA_WITH_TESTS_VALGRIND_OPTIONS="--error-exitcode=1;--leak-check=full;--fair-sched=yes;--gen-suppressions=all;--suppressions=$PWD/tools/valgrind/memcheck.supp" \
                -DPIKA_WITH_STACKOVERFLOW_DETECTION=Off \
                -DPIKA_WITH_CHECK_MODULE_DEPENDENCIES=On
      - name: Build
        shell: bash
        working-directory: build
        run: |
            ninja \
              tests.examples \
              tests.regressions.modules.coroutines \
              tests.unit.modules.assertion \
              tests.{regressions,unit}.modules.command_line_handling \
              tests.unit.modules.concurrency \
              tests.unit.modules.datastructures \
              tests.unit.modules.debugging \
              tests.unit.modules.errors \
              tests.{regressions,unit}.modules.execution \
              tests.unit.modules.execution_base \
              tests.{regressions,unit}.modules.functional \
              tests.unit.modules.memory \
              tests.{examples,regressions,unit}.modules.program_options \
              tests.unit.modules.properties \
              tests.{regressions,unit}.modules.resource_partitioner \
              tests.unit.modules.runtime \
              tests.unit.modules.schedulers \
              tests.unit.modules.string_util \
              tests.{performance,regressions,unit}.modules.synchronization \
              tests.unit.modules.tag_invoke \
              tests.unit.modules.threading \
              tests.{regressions,unit}.modules.threading_base \
              tests.unit.modules.topology \
              std_thread_scheduler_test
      - name: Test
        shell: bash
        run: |
            cd build
            ctest \
              -j $(nproc) \
              -L VALGRIND \
              --timeout 300 \
              --output-on-failure
