# Copyright (c) 2020-2022 ETH Zurich
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

name: macOS CI (Debug)

on:
  push:
    branches:
      # Development and release branches
      - main
      - release**
      # Bors branches
      - trying
      - staging

jobs:
  build_core:
    name: github/macos/debug
    runs-on: macos-latest

    steps:
    - name: Install dependencies
      run: |
        export HOMEBREW_NO_INSTALL_CLEANUP=TRUE
        brew upgrade
        brew update
        brew install boost cmake hwloc ninja
    - uses: actions/checkout@v2
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ccache-macos
    - name: Configure
      shell: bash
      run: |
          cmake \
              -H. \
              -Bbuild \
              -GNinja \
              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
              -DCMAKE_BUILD_TYPE=Debug \
              -DPIKA_WITH_UNITY_BUILD=ON \
              -DPIKA_WITH_EXAMPLES=ON \
              -DPIKA_WITH_TESTS=ON \
              -DPIKA_WITH_TESTS_HEADERS=OFF \
              -DPIKA_WITH_PARALLEL_TESTS_BIND_NONE=ON \
              -DPIKA_WITH_TESTS_MAX_THREADS=3 \
              -DPIKA_WITH_MALLOC=system \
              -DPIKA_WITH_CHECK_MODULE_DEPENDENCIES=ON \
              -DPIKA_WITH_COMPILER_WARNINGS=ON \
              -DPIKA_WITH_COMPILER_WARNINGS_AS_ERRORS=On
    - name: Build
      shell: bash
      run: |
          cmake --build build --target all
          cmake --build build --target tests
    - name: Test
      shell: bash
      run: |
          cd build
          ctest \
            -j3 \
            --output-on-failure \
            --timeout 300 \
            --exclude-regex \
          "tests.unit.modules.algorithms.default_construct|\
          tests.unit.modules.algorithms.destroy|\
          tests.unit.modules.algorithms.foreach_executors|\
          tests.unit.modules.algorithms.max_element|\
          tests.unit.modules.algorithms.replace_copy_if|\
          tests.unit.modules.execution.standalone_thread_pool_executor|\
          tests.unit.modules.resource_partitioner.used_pus"
    - name: Install
      shell: bash
      run: |
          cmake --build build --target install
    - name: Hello
      shell: bash
      run: |
          hello_world
